name: Changelog Update

on:
  push:
    branches:
      - master
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vemel/update-changelog@0.0.1
        id: changelog
        with:
          version: ${{ steps.version.outputs.version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Changelog update
          labels: changelog, update
          title: "Changelog update"
          body: |
            # Release ${{ steps.version.outputs.version }}

            Merge this PR to update your changelog!

            ## Included Pull Requests

            ${{ steps.changelog.outputs.pulls_list_md }}
