name: "Changelog auto update"

on:
  push:
    branches: [develop]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          allow-unknown: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update changelogs
          title: "Update changelogs"
          body: |
            # Update Changelogs

            Merge this PR to update your changelog!