name: "Changelog auto update"

on:
  push:
    branches: [develop]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update changelogs
          title: "Update changelogs"
          body: |
            # Update Changelogs

            ${{steps.github_release.outputs.changelog}}