name: "Changelog auto update"

on:
  push:
    tags: '*'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Create changelog
        id: changelog
        uses: loopwerk/tag-changelog@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/changelog.js
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'other: Update changelogs'
          title: "Update changelogs"
          body: ${{ steps.changelog.outputs.changes }}
