name: eslint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies 👨🏻‍💻
        run: npm i
      - name: Copy config example 📓
        run: cp config/config.example.json config/config.json
      - name: Run Linter ✏️
        run: npm run eslint