name: Sentry
on:
  push:
    branches:
      - develop
jobs:
  sentry_bot:
    name: Create sentry release and upload sourcemaps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Create sentry release and upload sourcemaps
        run: |
          npm run sentry:release
          npm run sentry:commits
          npm run sentry:sourcemaps
        env:
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          VERSION: ${{ github.sha }}